Fixes for minor issues with YR/Ares/Phobos
CnCNet/WorldAlteringEditor pull request #130
Opened 2024-03-03 18:30 UTC by Starkku

- Do not draw palette color #0 on voxels
- Fix empty voxel sections potentially causing an attempt to create zero-width/height `RenderTarget` texture
- Render voxel turret even if main voxel body is missing
- Render buildings even if their main shape file is empty or missing
- Improved palette selection for objects for YR/Ares/Phobos (supports `Palette` for all technos and wall OverlayTypes)
- Correctly use building's palette for building anims unless `ShouldUseCellDrawer` is set to false (this affects TS as well, as it works identically there)

2024-03-04 17:47 UTC, Starkku commented
>- Render voxel turret even if main voxel body is missing
>- Render buildings even if their main shape file is empty or missing

Realized that these can (and might actually be better off, because of how the sidebar preview textures are fetched currently) fixed via rules/art overrides. Consequently, I could drop them off this PR if needed.

2024-03-06 21:10 UTC, Rampastring requested changes
Looks good in general, a couple things to fix or explain.

Also, this PR breaks the contribution guidelines on PR scope, but with only 143 modified lines it's not too bad, so I'll let it pass this time.

2024-03-06 21:10 UTC, Rampastring commented on src/TSMapEditor/Rendering/ObjectRenderers/ObjectRenderer.cs
> +            if ((frame == null && !forceRender) && ShouldRenderReplacementText(gameObject))
Is there any good reason why you didn't modify the override of `ShouldRenderReplacementText` in `BuildingRenderer` and instead added this hack?

2024-03-06 21:10 UTC, Rampastring commented on src/TSMapEditor/Models/ArtConfig/AnimArtConfig.cs
> +        public bool ShouldUseCellDrawer { get; set; } = true; // Only used by building and tile animations
Make this comment a summary comment instead so it is easier to check from references.

2024-03-07 17:38 UTC, Starkku commented on src/TSMapEditor/Rendering/ObjectRenderers/ObjectRenderer.cs
> +            if ((frame == null && !forceRender) && ShouldRenderReplacementText(gameObject))
No, so I will change it.

2024-03-08 20:49 UTC, Rampastring approved these changes

2024-03-08 20:51 UTC, merged