Allow specific tilesets to connect to specific LAT types in editor
CnCNet/WorldAlteringEditor pull request #146
Opened 2024-04-04 17:34 UTC by Starkku

Allows LAT grounds to treat certain arbitrary tilesets as something that they can connect to (e.g not use transition tiles in between). Tileset indices can be listed for custom LAT grounds via `GroundNConnectTo` key and for the base 4 LAT types via keys (`Rough/Sand/Pave/GreenConnectToTileSets`) read from each theater in `Theaters.ini`. Latter is because these might be something that people want to change without touching the actual theater configuration INI game uses.

This is mostly something that can be used to fix sand & pavement LAT interactions in YR but I imagine it can potentially be used to great effect with the `GroundN` stuff elsewhere.

To apply the fixes for sand<->shores & pavement<->road & misc. pave tiles in YR config to match game's own behaviour with these tiles, set following for all theaters except LUNAR (and maybe URBAN although in this case it shouldn't have adverse effects either)
```ini
PaveConnectToTileSets=20,37,40
GreenConnectToTileSets=12
```

2024-04-06 03:49 UTC, Rampastring requested changes

2024-04-06 03:49 UTC, Rampastring commented on src/TSMapEditor/CCEngine/Theater.cs
> +        public List<string> GreenConnectToTileSets { get; set; }
Is there a reason why these exist as properties instead of just being handled like for the generic ground types, iow. read from the key at line 187?

2024-04-06 03:49 UTC, Rampastring commented on src/TSMapEditor/Mutations/Mutation.cs
> +                    g.TransitionTileSet.Index != baseTileSetId && g.BaseTileSet.Index == baseTileSetId);
Incorrect indentation - this is part of the statement that begins on the previous line so it should be intended 4 spaces more to the right

2024-04-07 09:57 UTC, Starkku commented on src/TSMapEditor/CCEngine/Theater.cs
> +        public List<string> GreenConnectToTileSets { get; set; }
I did mention this in the PR text, it is to allow setting these without touching the game's theater configuration INI.

2024-04-07 10:34 UTC, Rampastring commented on src/TSMapEditor/CCEngine/Theater.cs
> +        public List<string> GreenConnectToTileSets { get; set; }
Right.

I think optimally these could be read either from Theaters.ini or the game's theater config INI, if not specified in Theaters.ini. Could you edit the PR to make that possible?

2024-04-10 14:11 UTC, Starkku commented on src/TSMapEditor/CCEngine/Theater.cs
> +        public List<string> GreenConnectToTileSets { get; set; }
Done.

2024-04-10 19:20 UTC, Rampastring approved these changes

2024-04-10 19:20 UTC, merged