Allow script actions to use window for parameter selection
CnCNet/WorldAlteringEditor pull request #176
Opened 2024-06-11 22:04 UTC by Starkku

Pretty much what it says in the title, allows setting `UseWindowSelection` for script actions in `ScriptActions.ini` to use a selector window for the preset options (`OptionN`) key. Particularly useful (and needed) for certain Phobos script actions that use a list of values that far exceeds what the context menu can show.

A different button is displayed for opening the window on script actions that use it, from the one that opens the context menu.

2024-06-23 09:19 UTC, Rampastring requested changes

2024-06-23 09:19 UTC, Rampastring commented on src/TSMapEditor/Config/UI/Windows/ScriptsWindow.ini
> +$CC24=btnEditorPresetValuesWindow:EditorButton
```suggestion
$CC21=btnEditorPresetValues:MenuButton
$CC22=btnEditorPresetValuesWindow:EditorButton
$CC23=lblActionDescription:XNALabel
$CC24=panelActionDescription:EditorPanel
```

Since this exists visually in the same space as `btnEditorPresetValues`, and the `[btnEditorPresetValuesWindow]` section has been placed under the `[btnEditorPresetValues]` section, it would be logical for this to also be defined right below `btnEditorPresetValues` in the list.

2024-06-23 09:19 UTC, Rampastring commented on src/TSMapEditor/UI/Windows/ScriptsWindow.cs
> +                return;
```suggestion
            if (editedScript == null || lbActions.SelectedItem == null)
                return;
```

2024-06-23 09:19 UTC, Rampastring commented on src/TSMapEditor/UI/Windows/SelectScriptActionPresetOptionWindow.cs
> +                    item.TextColor = (Color)presetOption.Color;
```suggestion
                if (presetOption.Color.HasValue)
                    item.TextColor = presetOption.Color.Value;
```

Not really a complaint, I just prefer this syntax when working with nullable value types.

2024-06-23 09:19 UTC, Rampastring commented on src/TSMapEditor/CCEngine/ScriptAction.cs
> +        public Color? Color;
As far as I can see, there is currently no way to actually assign this a value? The INI parsing code for preset options is unchanged.

2024-06-23 09:19 UTC, Rampastring commented on src/TSMapEditor/CCEngine/ScriptAction.cs
> +        }
Unless I'm missing something, this constructor is never used, so it can be removed.

2025-07-22 18:05 UTC, Starkku commented
Rebased and feedback addressed.

2025-07-28 12:37 UTC, Rampastring approved these changes

2025-07-28 12:37 UTC, merged