Allow fill terrain modifier hotkey to apply to raise/lower cells
CnCNet/WorldAlteringEditor pull request #178
Opened 2024-06-11 22:12 UTC by Starkku

Allows holding the `Fill Terrain` hotkey while using the `Raise / Lower Individual Cells` tools to apply the action to an enclosed area similar to filling an area of cells with 1x1 tiles.

I was initially going to add its own customizable hotkey for this, but for sake of convenience and consistency I would have wanted both actions to use the same key, and current system does not allow mapping same key to multiple actions (for obvious reasons). So it was either this or hardcoding it to holding Ctrl or something.

2024-06-13 14:15 UTC, Rampastring requested changes
I fully support the idea of this.

However implementation-wise, I want the mutations to be as self-contained as possible.

Having `LowerCellsMutation` and `RaiseCellsMutation` depend on a mutation for an entirely different tool is unacceptable.

As far as I can see, the best way to solve this would be splitting `GetFillAreaTiles` into a helper function in another class, either in the existing `Helpers` or in its own file.

Another option would be making a base class mutation that supported gathering an area to fill and deriving `FillTerrainAreaMutation`, `LowerCellsMutation` and `RaiseCellsMutation` from it, but in this case I think that would be more complex and less flexible then simply having a static helper method.

2024-06-14 14:27 UTC, Starkku commented
Moved the helper function to `Helpers.cs`.

2024-06-17 20:33 UTC, Rampastring requested changes

2024-06-17 20:33 UTC, Rampastring commented on src/TSMapEditor/Mutations/Classes/HeightMutations/LowerCellsMutation.cs
>                      cell.Level--;
As far as I can see, there is nothing preventing this from being executed when the level is already at 0?

2024-06-17 20:33 UTC, Rampastring commented on src/TSMapEditor/Mutations/Classes/HeightMutations/RaiseCellsMutation.cs
>                      cell.Level++;
As far as I can see, there is nothing preventing this from being executed when the level is already at `Constants.MaxMapHeightLevel`?

2024-06-19 15:36 UTC, Starkku commented
Added the missing height checks.

2024-06-23 08:59 UTC, Rampastring approved these changes

2024-06-23 08:59 UTC, merged