Adjust helper functions to convert waypoints longer than 2 letters
CnCNet/WorldAlteringEditor pull request #180
Opened 2024-06-14 03:13 UTC by ZivDero

Adjusts the converted functions to handle waypoints past ZZ. Credits to (I think) secsome for the original implementation in Phobos.

2024-06-17 07:56 UTC, Starkku commented on src/TSMapEditor/Helpers.cs
> +            str = str.ToUpperInvariant();
Removing the null check here causes the editor to crash when trying to create new TeamType in the TeamTypes window, as the waypoint string on fresh TeamTypes defaults to null.

2024-06-17 07:58 UTC, ZivDero commented on src/TSMapEditor/Helpers.cs
> +            str = str.ToUpperInvariant();
Good point, fixed

2024-09-12 18:23 UTC, Rampastring requested changes

2024-09-12 18:23 UTC, Rampastring commented on src/TSMapEditor/Helpers.cs
> +                n += (c - 64) * j;
Put this `64` in a named constant. Yeah, we can figure out it's the char code of 'A' reduced by one, but it should be made obvious while reading the code.

2024-09-12 18:23 UTC, Rampastring commented on src/TSMapEditor/Helpers.cs
> +                waypointNumber = (waypointNumber - m) / 26;
Should reintroduce CharCount for this magic constant of 26.

2024-09-13 22:27 UTC, Rampastring approved these changes

2024-09-13 22:27 UTC, merged