Add Chinese manual document
CnCNet/WorldAlteringEditor pull request #215
Opened 2024-12-19 12:28 UTC by KuroNoSeiHai

Add Chinese manual document. And link  between Manual.md and Manual-CN.

2024-12-19 13:41 UTC, SadPencil requested changes
I will mark this Chinese translation as a borderline. A major revision is suggested. Please make your translation easily understood by Chinese people.

当前版本读起来很不通顺。

2024-12-19 13:41 UTC, SadPencil commented on docs/Manual-CN.md
> +# World-Altering Editor用户手册
Add a space between a Chinese character and an English alphabet

2024-12-19 13:41 UTC, SadPencil commented on docs/Manual-CN.md
> +我们试图使编辑器的用户界面更加直观易用，但如果您仍有困惑，本指南包含一些有用的提示和技巧。
Please focus on writing simple and natural sentences rather than directly translating every English word.

2024-12-19 13:41 UTC, SadPencil commented on docs/Manual-CN.md
> +我们试图使编辑器的用户界面更加直观易用，但如果您仍有困惑，本指南包含一些有用的提示和技巧。
This line requires polishing.

2024-12-19 13:41 UTC, SadPencil commented on docs/Manual-CN.md
> +**注意:** 本手册提及的许多快捷键，都可以在 *Keyboard Options* 菜单进行自定义。本指南仅使用默认值进行说明。
Avoid translating every English word directly. The placement of the word `许多` is awkward in Chinese.

2024-12-19 13:41 UTC, SadPencil commented on docs/Manual-CN.md
> +要绘制地形，请从顶部栏或屏幕底部的 TileSet 选择器中选择一个地块。然后你只需点击一下就把可以它放在地图上。
`然后你只需点击一下`: consider removing the word `你` (you) since in Chinese it's more often to omit obvious subject, especially on imperative sentences.

`就把可以它放在地图上`: Please carefully proofreading your Chinese sentences. Try avoiding such obvious careless mistakes. Also, it is advisable to use written language instead of oral language, e.g., `将其放置在地图上` .

2024-12-19 13:41 UTC, SadPencil commented on docs/Manual-CN.md
> +**要填充封闭区域**, 请选择一个 1x1 大小的图块，然后在按住 Ctrl 的同时单击该区域。此逻辑类似于微软画图软件或许多其他图像和地图编辑器中的“油漆桶工具”。
The phrase `many other image and map editors` indicates that there are several image editors and several map editors, not that there are editors that support editing both images and maps.

2024-12-19 13:41 UTC, SadPencil commented on docs/Manual-CN.md
> +要绘制水面，请从屏幕底部的 TileSet 选择器中选择 Water TileSet。然后就可以一块一块地绘制。您可以增加笔刷大小以覆盖更大的区域，或使用上述的填充功能。
`然后就可以一块一块地绘制`: the original English text `Then a tile and paint` seems incorrect. Wait for the correction.

`或使用上述的填充功能`: as far as I know (beat me if I am wrong), `上述` can only refer to a thing that is just mentioned. Referring to a thing that is 2 paragraph away might be confusing. Try using something like `在上一节中提到的` / `mentioned in the previous section`

2024-12-19 13:41 UTC, SadPencil commented on docs/Manual-CN.md
> +完成地图细节处理后，您可以运行，你可以运行 *Tools -> Run Script... -> Smoothen Water.cs*。该脚本将随机化地图上的所有水地形块。
`您可以运行，你可以运行`: Proofreading required.

2024-12-19 13:41 UTC, SadPencil commented on docs/Manual-CN.md
> +完成地图细节处理后，您可以运行，你可以运行 *Tools -> Run Script... -> Smoothen Water.cs*。该脚本将随机化地图上的所有水地形块。
Also, try to avoid directly translate `randomize` with the Chinese word `随机化`. It is correct, but the Chinese word is less frequently used. Try paraphrase it.

2024-12-19 13:41 UTC, SadPencil commented on docs/Manual-CN.md
> +通常，地形块位于光标上方。这会让在地图的南部边缘放置地形块变得不方便。在这种情况下，您可以按住 Alt 键将地形块放置在光标下方，而不是光标上方。
`这会让在地图的南部边缘放置地形块变得不方便`: sentences like this one should be paraphrased with a comma, i.e., you can use two Chinese sentences here to represent the same meaning that a single English sentence convey. Don't just translate each word one by one if you find the translation awkward in Chinese.

2024-12-19 13:41 UTC, SadPencil commented on docs/Manual-CN.md
> +与大多数程序一样，Ctrl+C 和 Ctrl+V 键启用常规矩形复制和粘贴功能。也可以从 Edit 菜单访问它们。
An English sentence often uses an object (rather than, for example, a person) as the subject. When translating into Chinese, consider changing the subject if it feels awkward.

2024-12-19 13:41 UTC, SadPencil commented on docs/Manual-CN.md
> +Alt+C 可激活复制自定义形状区域的工具。
Same as above. In Chinese, you can use "doing sth" as the subject, but using "sth" (an object) as the subject is often awkward.

2024-12-19 13:41 UTC, SadPencil commented on docs/Manual-CN.md
> +有时，您可能想要复制的不仅仅是地形：建筑物、单位、树木、覆盖物等。您可以从  *Edit -> Configure Copied Objects* 中选择要复制的地图元素。
`复制的不仅仅是地形`: again, please paraphrase awkward Chinese sentences. Why not translate it like `复制非地形元素`?

2024-12-19 13:41 UTC, SadPencil commented on docs/Manual-CN.md
> +要绘制地形，请从顶部栏或屏幕底部的 TileSet 选择器中选择一个地块。然后你只需点击一下就把可以它放在地图上。
I will omit the suggestion on removing the obsolete subject "you" on imperative sentences. Please pay attention all the time.

2024-12-19 13:41 UTC, SadPencil commented on docs/Manual-CN.md
> +另一种方法是按 *Deletion Mode* 顶部栏上的按钮。它会激活一个删除光标，您可以使用该光标通过单击地图上的对象来删除对象。
`您可以使用该光标通过单击地图上的对象来删除对象`: again, please paraphrase awkward sentences.

2024-12-19 13:41 UTC, SadPencil commented on docs/Manual-CN.md
> +默认情况下，WAE 会阻止您重叠对象（将多个单位或建筑物放置在同一个格子上）以避免一些意外。这对 泰伯利亚之日 尤其重要，因为如果多个建筑物重叠，游戏可能会崩溃——这是粉丝制作地图中的常见错误。
`因为如果多个建筑物重叠，游戏可能会崩溃`: I will paraphrase this sentence for you, as an example. `因为多个建筑物重叠可能会导致游戏崩溃`.

2024-12-19 13:41 UTC, SadPencil commented on docs/Manual-CN.md
> +默认情况下，WAE 会阻止您重叠对象（将多个单位或建筑物放置在同一个格子上）以避免一些意外。这对 泰伯利亚之日 尤其重要，因为如果多个建筑物重叠，游戏可能会崩溃——这是粉丝制作地图中的常见错误。
`粉丝制作地图`: Personally I think it's better to translate `fan-made maps` as `自制地图` due to the naming preference of 3rd party maps, although the meaning is slightly changed. You can ignore this comment if you have a different opinion.

2024-12-19 13:41 UTC, SadPencil commented on docs/Manual-CN.md
> +如果您有意要重叠对象，请在放置或移动对象时按住 Alt 键，WAE 允许您重叠它们。
In Chinese, the verb is not explicitly classified as vt. and vi. Often, if the word `它们/它` (them/it) appears after the verb, you can just assume the verb as vi. and remove the word `它们/它` (them/it).

2024-12-19 13:41 UTC, SadPencil commented on docs/Manual-CN.md
> +如果要重置为默认缩放级别，请按键盘上的 `Ctrl + 0` 就像在您的 Web 浏览器中一样。
> 请按键盘上的 `Ctrl + 0` 就像在您的 Web 浏览器中一样。
Clearly, a comma is mandatory before `就像` here.

2024-12-19 13:41 UTC, SadPencil commented on docs/Manual-CN.md
> +您可以通过按 F11 打开或关闭全屏模式，无论您是在全屏模式还是窗口模式下启动的 WAE。
Re-order these two sentences. Also `通过` here seems obsolete.

2024-12-19 13:41 UTC, SadPencil commented on docs/Manual-CN.md
> +如果您有多显示器，则当使用 F11 最大化时，WAE 会在按 F11 时正在打开的窗口显示器进行全屏。
`WAE 会在按 F11 时正在打开的窗口显示器进行全屏。` Proofreading required.

2024-12-19 13:41 UTC, SadPencil commented on docs/Manual-CN.md
> +如果您有多显示器，则当使用 F11 最大化时，WAE 会在按 F11 时正在打开的窗口显示器进行全屏。
`则当使用 F11 最大化时` The subject should not be omitted here since "WAE" is not the subject who hits the F11 key.

2024-12-19 13:41 UTC, SadPencil commented on docs/Manual-CN.md
> +**自动保存不会覆写您打开的地图文件**, 而是将以 `autosave.map` 保存到 WAE 的目录中。如果您遇到崩溃或其他会导致工作丢失的问题，您可以从 WAE 的目录中找到该文件，复制它并继续您的工作。
I think it's more common to use `覆盖文件` for `overwriting a file`, instead of `覆写`.

2024-12-19 13:41 UTC, SadPencil commented on docs/Manual-CN.md
> +**自动保存不会覆写您打开的地图文件**, 而是将以 `autosave.map` 保存到 WAE 的目录中。如果您遇到崩溃或其他会导致工作丢失的问题，您可以从 WAE 的目录中找到该文件，复制它并继续您的工作。
`而是将以 `autosave.map` 保存到 WAE 的目录中`: Proofreading.

2024-12-19 13:41 UTC, SadPencil commented on docs/Manual-CN.md
> +**自动保存不会覆写您打开的地图文件**, 而是将以 `autosave.map` 保存到 WAE 的目录中。如果您遇到崩溃或其他会导致工作丢失的问题，您可以从 WAE 的目录中找到该文件，复制它并继续您的工作。
`复制它并继续您的工作。` Please make the verb `复制` as vi. and remove the object `它`.

2024-12-20 04:35 UTC, SadPencil requested changes

2024-12-20 04:35 UTC, SadPencil commented on docs/Manual-CN.md
> +**要填充封闭区域**, 请选择一个 1x1 大小的图块，然后在按住 Ctrl 的同时单击该区域。此逻辑类似于微软画图软件、很多其他图像编辑软件或很多其他地图编辑器中的“油漆桶工具”。
Why repeating 很多其他?

2024-12-20 04:35 UTC, SadPencil commented on docs/Manual-CN.md
> +**自动保存不会覆盖您打开的地图文件**, 而是将另存一个 `autosave.map` 文件到 WAE 的目录中。如果您遇到崩溃或其他导致工作丢失的问题，您可以从 WAE 的目录中找到该文件，复制并继续您的工作。
You should paraphrase whenever the sentence is weird. Why not use 找到并复制该文件?

2024-12-20 04:35 UTC, SadPencil commented on docs/Manual-CN.md
> +如果您有多显示器，则当您使用 F11 最大化时，WAE 会在自己所在的显示器全屏。
The word 自己 does not sound like formal. Use 当前 instead.

2024-12-20 04:35 UTC, SadPencil commented on docs/Manual-CN.md
> +默认情况下，WAE 会阻止您重叠对象（将多个单位或建筑物放置在同一个格子上）以避免一些意外。这对 泰伯利亚之日 尤其重要，因为如果多个建筑物重叠，游戏可能会崩溃——这是自制地图中的常见错误。
I left a comment that I would omit same comments for omitting the subject you in imperative sentences. Not just the sentence I have pointed out.

2024-12-20 04:35 UTC, SadPencil commented on docs/Manual-CN.md
> +另一种方法是按 *Deletion Mode* 顶部栏上的按钮。它会激活一个删除光标，然后您可以单击地图上的对象来删除。
Unclear reference of the word 它.

2024-12-20 04:35 UTC, SadPencil commented on docs/Manual-CN.md
> +完成地图细节处理后，您可以运行 *Tools -> Run Script... -> Smoothen Water.cs*。该脚本将随机化地图上的所有水地形块。
The last comment said it's better to avoid using the word 随机化. Use something like 随机替换 instead.

2024-12-20 04:35 UTC, SadPencil commented on docs/Manual-CN.md
> +要绘制水面，请从屏幕底部的 TileSet 选择器中选择 Water TileSet。然后请选择一个地图格子进行绘制。您可以增加笔刷大小以覆盖更大的区域，或使用在上一节中提到的填充功能。
The word 格子 is too oral. Please use exactly the same Chinese word among the whole translation to describe this thing. Not randomly using 格子/地块/图块/地形块, etc.

2024-12-20 04:37 UTC, SadPencil commented
Also, I marked some previous comments as unsolved. Address them as well.

2024-12-20 11:20 UTC, SadPencil requested changes
Also, I marked some previous comments as unsolved. Address them as well.

2024-12-20 11:35 UTC, KuroNoSeiHai commented on docs/Manual-CN.md
> +要绘制水面，请从屏幕底部的 TileSet 选择器中选择 Water TileSet。然后请选择一个地图格子进行绘制。您可以增加笔刷大小以覆盖更大的区域，或使用在上一节中提到的填充功能。
地块 means map cell, 地形块 means tileset

2024-12-20 14:05 UTC, SadPencil requested changes
There are still minor issues that have been mentioned before. Please proofread it again. I'll contact you in private.

2024-12-23 07:17 UTC, SadPencil approved these changes

2025-01-13 02:50 UTC, merged