Add Animations, building ActiveAnims and turrets
CnCNet/WorldAlteringEditor pull request #34
Opened 2023-07-08 22:22 UTC by MortonPL

Closes #25 and #28. This PR includes:

* parsing and rendering of Animations, specifically building turrets and ActiveAnims,
* new Constants option, `ReverseFacing`, as RA2/YR facings are counter-clockwise (this affects infantry as well),
* correct BibShape drawing for NewTheater art.

To-do:
Parse and display building SpecialAnims.

2023-07-31 14:56 UTC, Rampastring requested changes
Looks good for the most part. There's a few stylistical issues.

`ReverseFacing` is likely unnecessary as the reversing is most likely correct also for TS. You can remove it or leave it in, in which case I'll remove it later if it actually turns out to be unnecessary in testing.

2023-07-31 14:56 UTC, Rampastring commented on src/TSMapEditor/Models/Animation.cs
> +    public class Animation: GameObject
Leave a space between the class name and the `:`.

2023-07-31 14:56 UTC, Rampastring commented on src/TSMapEditor/Models/ArtConfig/AnimArtConfig.cs
> +    public class AnimArtConfig: IArtConfig
Leave a space between the class name and the `:`.

2023-07-31 14:56 UTC, Rampastring commented on src/TSMapEditor/Config/Constants.ini
> +ReverseFacing=false
This is likely unnecessary, as WAE has actually had bugged infantry facings in TS so far. Maybe using the logic with this setting on `true` also fixes them for TS. I don't know about turrets because WAE hasn't rendered them yet.

2023-07-31 14:56 UTC, Rampastring commented on src/TSMapEditor/Models/Structure.cs
> +                if (TurretAnim != null)
Put some spacing here.

```cs
                _position = value;

                foreach (var anim in ActiveAnims)
                    anim.Position = value;

                if (TurretAnim != null)
                    TurretAnim.Position = value;
```

2023-07-31 14:56 UTC, Rampastring commented on src/TSMapEditor/Models/Structure.cs
> +            }
See above note about spacing. Also braces `{ }` in the `foreach` are unnecessary.

2023-07-31 14:56 UTC, Rampastring commented on src/TSMapEditor/Models/Structure.cs
> +            }
See above note about spacing.

2023-07-31 14:56 UTC, Rampastring commented on src/TSMapEditor/Rendering/TheaterGraphics.cs
> +
Unnecessary blank line.

2023-08-09 04:30 UTC, ZivDero commented
There appear to be Z-sorting issues
![1](https://github.com/Rampastring/TSMapEditor/assets/5639388/60252f21-64c8-410e-b844-56b6f7185263)
![2](https://github.com/Rampastring/TSMapEditor/assets/5639388/ea45e425-8c99-4a7f-b292-323d88cda082)

2023-08-12 01:02 UTC, ZivDero commented
Also I think it fails when a building has a turret, but no turret images (e. g. the Component Tower). Please check that.

2023-08-27 15:39 UTC, Rampastring approved these changes

2023-08-27 15:39 UTC, merged