Add map lighting
CnCNet/WorldAlteringEditor pull request #35
Opened 2023-07-08 22:33 UTC by MortonPL

Closes #29. This PR, once prerequisites are met, will add mapwide color tinting with values defined in `[Lighting]` section.
A new Constants option is added, `TiberiumAffectedByLighting`, to toggle between TS/YR behavior and apparent DTA behavior.

To-dos:
* Toggle between "no light", "map light", "storm light",
* Support for palette indices not affected by light (requires renderer rewrite),
* Support for `Ground` value, tile light affected by cell height.

2024-02-19 18:56 UTC, ZivDero commented on src/TSMapEditor/Models/Lighting.cs
> +                return Color.White;
Could this result in DOminator lighting being set to white in a TS map and then written to the map pointlessly?

2024-02-19 21:16 UTC, MortonPL commented on src/TSMapEditor/Models/Lighting.cs
> +                return Color.White;
`NormalColor`, `IonColor` and `DominatorColor` should not be serialized now.

2024-02-20 17:51 UTC, Rampastring requested changes
Looks mostly good, there's a few things to fix or improve.

2024-02-20 17:51 UTC, Rampastring commented on src/TSMapEditor/Config/Constants.ini
> +TerrainObjectsAffectedByLighting=false
`TerrainObjectsAffectedByLighting` sounds like it'd affect all terrain objects, while the comment says that this key would only affect Tiberium-spawning terrain objects. Give the INI key a name that matches its purpose better.

2024-02-20 17:51 UTC, Rampastring commented on src/TSMapEditor/Models/Lighting.cs
> +        public event EventHandler Changed;
Reading the code below, a more appropriate name would be `ColorsRefreshed` than `Changed`. I'd expect a `Changed` event to trigger when the individual color components are changed.

2024-02-20 17:51 UTC, Rampastring commented on src/TSMapEditor/Rendering/TheaterGraphics.cs
> +            animPalette.ApplyLighting(lighting);
The `palettes` list also contains these standard palettes, so these lines are unnecessary.

2024-02-20 17:51 UTC, Rampastring commented on src/TSMapEditor/Rendering/TheaterGraphics.cs
> +            RemapFrames.Clear();
You need to dispose all `Texture2D` instances within these or you will be leaking GPU memory.

2024-02-20 17:51 UTC, Rampastring commented on src/TSMapEditor/UI/Windows/LightingSettingsWindow.cs
> +            };
You could add numbers to the values of the `LightPreviewMode` enum so this could be simplified to `state.LightingPreviewState = (LightingPreviewMode)ddLightingPreview.SelectedIndex.

The lines beween 108 and 112 could then also be similarly replaced.

2024-02-20 18:06 UTC, ZivDero commented on src/TSMapEditor/Config/Constants.ini
> +TerrainObjectsAffectedByLighting=false
TerrainObjects -> Tibtree?

2024-02-22 16:56 UTC, MortonPL commented on src/TSMapEditor/UI/Windows/LightingSettingsWindow.cs
> +            };
I disagree, these enum variants shouldn't have assigned integer values.
Things like `state.LightingPreviewState = (LightingPreviewMode)99` should not be allowed.

2024-02-22 17:29 UTC, Rampastring commented on src/TSMapEditor/UI/Windows/LightingSettingsWindow.cs
> +            };
I'd agree if this was somehow decoupled from indexes in general, but it's already tied to the selected index of `ddLightingPreview`. If you want to avoid stuff like `(LightingPreviewMode)99`, you could check the value with `Enum.IsDefined` and fall back to `LightingPreviewMode.NoLighting` if the value is nonsensical. You could do it pretty cleanly in the setter in `EditorState.LightingPreviewState`.

2024-02-23 15:10 UTC, Rampastring approved these changes

2024-02-23 15:10 UTC, merged