Example configuration for YR
CnCNet/WorldAlteringEditor pull request #36
Opened 2023-07-08 23:25 UTC by MortonPL

This PR provides an example configuration for Yuri's Revenge and YR-based modifications. It's targeting branch `tsclient` for now to minimize diff, but, once complete, it should ideally become an upstream branch.

Current configuration contains most of the necessary map making things, but it is currently missing mission scripting data like new trigger events, actions and script actions.

2023-12-27 16:58 UTC, ZivDero commented
Removed all the code changes from this branch, now it only consists of config changes. (Except for the last few commits, consider splitting them).
Rebased onto the latest TS config.

2024-01-07 14:22 UTC, Rampastring requested changes

2024-01-07 14:22 UTC, Rampastring commented on src/TSMapEditor/Config/Actions.ini
> +Name=Play Sound
I'd like both trigger/script action names and descriptions to be uniform across editor configurations, for the actions that are shared between TS and YR. If you feel they can be improved, make a PR for it targeting `master` rather than editing them for YR alone.

2024-01-07 14:26 UTC, ZivDero commented on src/TSMapEditor/Config/Actions.ini
> +Name=Play Sound
> I'd like both trigger/script action names and descriptions to be uniform across editor configurations, for the actions that are shared between TS and YR. If you feel they can be improved, make a PR for it targeting `master` rather than editing them for YR alone.

I totally agree. Will need to put some thought into stadardizing it, though, as rn it's a mish-mash of FA2/FS, ModEnc and "freestyle".

2024-01-08 00:13 UTC, Rampastring approved these changes

2024-01-08 00:17 UTC, merged