Added Hotkey for Save
CnCNet/WorldAlteringEditor pull request #41
Opened 2023-07-31 23:16 UTC by EliasMasche

Added a new hotkey functionality for Saving maps with `Ctrl + S` and refactored the lambda expression into its own function

2023-08-02 21:06 UTC, Rampastring requested changes
Looks good aside from a couple of stylistical issues.

2023-08-02 21:06 UTC, Rampastring commented on src/TSMapEditor/UI/TopBar/TopBarMenu.cs
> +            fileContextMenu.AddItem("Save", () => { SaveMap(); });
Unnecessary brackets `{` `}` in the lambda expression. See the SaveAs one below for reference.

2023-08-02 21:06 UTC, Rampastring commented on src/TSMapEditor/UI/TopBar/TopBarMenu.cs
> +            KeyboardCommands.Instance.Save.Triggered += (s, e) => { SaveMap(); };
Same here.

2023-08-02 21:21 UTC, EliasMasche commented
Updated commit with removal of unnecessary brackets

2023-08-03 16:48 UTC, Rampastring approved these changes

2023-08-03 16:48 UTC, merged