Allow multiple objects in cell
CnCNet/WorldAlteringEditor pull request #48
Opened 2023-08-09 03:00 UTC by ZivDero

This PR converts Waypoint, Aircraft, Vehicle and Structure into Lists, allowing to place multiple of those entities in a single cell, which is supported by the game engine.

2023-08-09 16:51 UTC, Rampastring requested changes
The game does not fully support this functionality. In particular, if buildings placed on top of each other, the game crashes if one of them is destroyed. This was a common mapping error with FinalSun/FinalAlert, which WAE was designed to prevent.

There are still a couple of good reasons for in turning a cell's buildings into a list though:

1) it has use for buildings that are converted to overlay. For example, placing a crate building with `ToOverlay=CRATE` under a real destroyable building, to add a collectible crate that the player can pick up after destroying the building
2) supporting maps that already have overlapping buildings

However I don't think WAE should allow placing overlapping buildings by default. Instead this should be behind some modifier key, so the mapper can't accidentally make buildings overlap, but instead it's always a deliberate action.

For units, aircraft and waypoints there is no such issue AFAIK, but is it _beneficial_ to allow them to overlap? I have a hard time imagining a case where making units overlap would be very useful. It could still be allowed with the modifier key, but I'd also prevent it by default.

For the implementation, I think the current implementation might crash when deleting objects as you're modifying a collection that is being foreach'd. Deletion should instead act on a copy of the list.

2023-08-09 16:58 UTC, ZivDero commented
I actually strongly disagree with this reasoning, as YR does in fact fully support this and does not crash (whether the buildings are invincible or not). Although it seems that invincile buildings also get damaged when the vulnerable ones receive damage. I suppose adding a modifyer key wouldn't hurt, though.

As for deletion, in my tests it did not crash but I agree that this is not a safe way to do it indeed so will redo.

2023-08-13 00:42 UTC, ZivDero commented
Okay, all done. I've added Alt as the default hotkey that allows to place overlapping objects. Works for placing new buildings, moving/cloning buildings, as well as the Terrain copy tool. Don't think I've missed anything.

2023-08-16 15:49 UTC, Rampastring requested changes
Functionality looks good now.

There are some stylistical things to fix, including some harmful renames.

2023-08-16 15:49 UTC, Rampastring commented on src/TSMapEditor/Models/MapTile.cs
> +            if (Structures.Count > 0)
Looks like a copy/paste error.

2023-08-16 15:49 UTC, Rampastring commented on src/TSMapEditor/Mutations/Classes/PasteTerrainMutation.cs
> +                    foreach (var vehicle in cell.Vehicles)
Only statements at the most indented level can be braceless. Iow. add braces to this `foreach`.

2023-08-16 15:49 UTC, Rampastring commented on src/TSMapEditor/Mutations/Classes/PasteTerrainMutation.cs
> +                        foreach (var building in foundationCell.Structures)
Only statements at the most indented level can be braceless. Iow. add braces to this `foreach`.

2023-08-16 15:49 UTC, Rampastring commented on src/TSMapEditor/UI/CursorActions/AircraftPlacementAction.cs
> -        private AircraftType _aircraftType;
Keep the underscore in names of fields that only exist to back a property.

2023-08-16 15:49 UTC, Rampastring commented on src/TSMapEditor/UI/CursorActions/AircraftPlacementAction.cs
> +
Pointless blank line.

2023-08-16 15:49 UTC, Rampastring commented on src/TSMapEditor/UI/CursorActions/AircraftPlacementAction.cs
> +                overlapObjects);
This line isn't long enough to warrant cutting it.

2023-08-16 15:49 UTC, Rampastring commented on src/TSMapEditor/UI/CursorActions/BuildingPlacementAction.cs
> -        private BuildingType _buildingType;
Keep the underscore in names of fields that only exist to back a property.

2023-08-16 15:49 UTC, Rampastring commented on src/TSMapEditor/UI/CursorActions/InfantryPlacementAction.cs
> -        private InfantryType _infantryType;
Keep the underscore in names of fields that only exist to back a property.

2023-08-16 15:49 UTC, Rampastring commented on src/TSMapEditor/UI/CursorActions/OverlayCollectionPlacementAction.cs
> -        private OverlayCollection _overlayCollection;
Keep the underscore in names of fields that only exist to back a property.

2023-08-16 15:49 UTC, Rampastring commented on src/TSMapEditor/UI/CursorActions/OverlayPlacementAction.cs
> -        private OverlayType _overlayType;
Keep the underscore in names of fields that only exist to back a property.

2023-08-16 15:49 UTC, Rampastring commented on src/TSMapEditor/UI/CursorActions/TerrainObjectPlacementAction.cs
> -        private TerrainType _terrainType;
Keep the underscore in names of fields that only exist to back a property.

2023-08-16 15:49 UTC, Rampastring commented on src/TSMapEditor/UI/CursorActions/UnitPlacementAction.cs
> -        private UnitType _unitType;
Keep the underscore in names of fields that only exist to back a property.

2023-08-16 15:49 UTC, Rampastring commented on src/TSMapEditor/Initialization/MapLoader.cs
> +                        Logger.Log($"NOTE: Building {buildingType.ININame} exists in the cell {cellCoords} that already has other buildings.");
Can improve this a bit (both grammar and accuracy wise).

```suggestion
                        Logger.Log($"NOTE: Building {buildingType.ININame} exists in a cell {cellCoords} that already has one or more buildings.");
```

2023-08-16 15:49 UTC, Rampastring commented on src/TSMapEditor/Initialization/MapLoader.cs
> +                    Logger.Log($"NOTE: Waypoint {waypoint.Identifier} exists in the cell {waypoint.Position} that already has other waypoints.");
Can improve this a bit (both grammar and accuracy wise).
```suggestion
                    Logger.Log($"NOTE: Waypoint {waypoint.Identifier} exists in a cell {waypoint.Position} that already has one or more waypoints.");
```

2023-08-16 15:49 UTC, Rampastring commented on src/TSMapEditor/Models/Map.cs
> +                Logger.Log($"NOTE: Waypoint {waypoint.Identifier} exists in the cell {cell.CoordsToPoint()} that already has other waypoints.");
Can improve this a bit (both grammar and accuracy wise).
```suggestion
                Logger.Log($"NOTE: Waypoint {waypoint.Identifier} exists in a cell {waypoint.Position} that already has one or more waypoints.");
```

2023-08-16 15:52 UTC, ZivDero commented on src/TSMapEditor/UI/CursorActions/UnitPlacementAction.cs
> -        private UnitType _unitType;
The underscores actually confused me since from what I could tell, the C# convention was to use _camelCase for all private fields, not just ones that back properties. So it seemed reasonable to either use it everywhere (which I didn't see happen much), or not use it at all. I guess what you said also can make sense?

2023-08-16 16:25 UTC, ZivDero commented
Implemented the requested changes.

2023-08-16 18:14 UTC, Rampastring approved these changes

2023-08-16 18:14 UTC, Rampastring commented on src/TSMapEditor/UI/CursorActions/TerrainObjectCollectionPlacementAction.cs
> +        private TerrainObjectCollection terrainObjectCollection;
Here is one more removed underscore.

2023-08-16 18:15 UTC, merged