Add Ares/Phobos style INI include for game INIs
CnCNet/WorldAlteringEditor pull request #7
Opened 2023-06-17 22:48 UTC by MortonPL

This PR adds support for [Ares](https://ares-developers.github.io/Ares-docs/new/misc/include.html) and [Phobos](https://phobos.readthedocs.io/en/latest/Miscellanous.html#include-files) INI include feature and [Phobos INI section inheritance](https://phobos.readthedocs.io/en/latest/Miscellanous.html#section-inheritance) feature for rules, art, theme and theater INIs. Map editor config files are not affected by this change.

Wasn't sure where to put this new `IniFileEx`, so I created a temporary directory `Extensions`.

Example use case of linked features:

`rulesmd.ini`:
```ini
[$Include]
0=new_rules.ini
```

`new_rules.ini`:
```ini
[E2]
$Inherits=SOVIET_OWNERS
; no Owner defined here

[SOVIET_OWNERS]
Owner=Russians,Confederation,Africans,Arabs
```

2023-06-18 07:26 UTC, Rampastring requested changes
One stylistical issue, looks good otherwise.

I see that it only supports Ares OR Phobos include sections, you can't use both at the same time in YR?

I also wonder whether going through all sections like this can have a performance hit on map (incl. rules) load time. If yes, this should be made an optional toggle. Although the effect is probably insignificant enough to not really matter. Have you observed any difference?

2023-06-18 07:26 UTC, Rampastring commented on src/TSMapEditor/Extensions/IniFileEx.cs
> +                foreach (var pair in parent.Keys)
Add braces for this `foreach`. Don't nest braceless expressions.

2023-06-18 13:23 UTC, Metadorius commented
> Ares OR Phobos include sections, you can't use both at the same time in YR?

Correct. The hooks conflict with each other and enabling Phobos implementation disables Ares.

2023-06-27 18:09 UTC, MortonPL commented
> I also wonder whether going through all sections like this can have a performance hit on map (incl. rules) load time. If yes, this should be made an optional toggle. Although the effect is probably insignificant enough to not really matter. Have you observed any difference?

It wasn't noticeable for vanilla YR rules, but I've made this addition opt-in anyway.

2023-06-29 07:49 UTC, Rampastring approved these changes

2023-06-29 07:50 UTC, merged