Add bridge drawing tool
CnCNet/WorldAlteringEditor pull request #70
Opened 2023-09-30 21:58 UTC by ZivDero

2023-10-05 23:17 UTC, Rampastring requested changes
Looks good for the most part, some small things to adjust.

2023-10-05 23:17 UTC, Rampastring commented on src/TSMapEditor/Config/UI/Windows/SelectBridgeWindow.ini
> +$Height=RESOLUTION_HEIGHT - 100
This is probably comically big for a list that will most of the time have only like 3 entries.

2023-10-05 23:17 UTC, Rampastring commented on src/TSMapEditor/Models/Bridge.cs
> +                Pieces.Add(bridgePiece);
Add an empty line after reach `throw new ...` statement in these entire `if-else` blocks, it's going to look clearer.

2023-10-05 23:17 UTC, Rampastring commented on src/TSMapEditor/Models/Bridge.cs
> +                    throw new BridgeLoadException($"Low bridge {bridge.Name} has no bridge pieces!");
Shouldn't this be also checked for high bridges? Could the check be moved outside the `if-else` structure?

2023-10-05 23:17 UTC, Rampastring commented on src/TSMapEditor/Models/Bridge.cs
> +    public class Bridge
I think the name of this class can be confused with a bridge that is actually placed on the map, instead of being a container for a specific type of bridge.

Renaming it to `BridgeType` would solve the issue. Kinda like we have `UnitType` and `Unit`.

2023-10-05 23:17 UTC, Rampastring commented on src/TSMapEditor/Rendering/ObjectRenderers/OverlayRenderer.cs
> +            }
This is a bit ugly. Maybe overlay types should instead contain a `HighBridgeType` property that was assigned to all bridge-related overlay in the initialization phase.

That being said, this is fine for now. If it turns out to cause issues at some later point in time, we can refactor it then.

2023-10-05 23:26 UTC, ZivDero commented on src/TSMapEditor/Models/Bridge.cs
> +                    throw new BridgeLoadException($"Low bridge {bridge.Name} has no bridge pieces!");
This behavior is correct. For low bridges, there is a list of overlays that serve as sections (thus the count check), but for high bridges there is one overlay which has multiple frames instead.

`string piece = iniSection.GetStringValue($"BridgePieces.{suffix}", null);
if (piece == null)
    throw new BridgeLoadException($"High bridge {bridge.Name} has no bridge piece!");

int bridgePiece = rules.FindOverlayType(piece)?.Index ??
      throw new BridgeLoadException($"High bridge {bridge.Name} has an invalid bridge piece {piece}!");`

These checks should be sufficient.

2023-10-07 11:27 UTC, Rampastring approved these changes

2023-10-07 11:28 UTC, merged