Connected Overlay Painting Tool
CnCNet/WorldAlteringEditor pull request #75
Opened 2023-11-09 21:38 UTC by ZivDero

This PR adds a tool to paint overlays that connect (i. e. walls and tracks).
The overlays to be painted are fully configurable in ConnectedOverlays.ini

2023-11-11 21:12 UTC, Rampastring requested changes
Some stylistical and some implementation-related things to improve.

2023-11-11 21:12 UTC, Rampastring commented on src/TSMapEditor/Models/ConnectedOverlayType.cs
> +    public class ConnectedOverlayType
```suggestion

    public class ConnectedOverlayType
```

2023-11-11 21:12 UTC, Rampastring commented on src/TSMapEditor/Models/ConnectedOverlayType.cs
> +            if (connectionMaskString == null || connectionMaskString.Length != 8 || Regex.IsMatch(connectionMaskString, "[^01]"))
```suggestion
            if (connectionMaskString == null || connectionMaskString.Length != Direction.Count || Regex.IsMatch(connectionMaskString, "[^01]"))
```

2023-11-11 21:12 UTC, Rampastring commented on src/TSMapEditor/Models/ConnectedOverlayType.cs
> +            ConnectionMask = new BitArray(connectionMaskString.Select(c => c == '1').ToArray());
```suggestion

            ConnectionMask = new BitArray(connectionMaskString.Select(c => c == '1').ToArray());
```

2023-11-11 21:12 UTC, Rampastring commented on src/TSMapEditor/Models/ConnectedOverlayType.cs
> +                              throw new Exception($"Connected overlay type {i} has an invalid overlay name {overlayName}!");
Currently this does not actually tell the type, but the frame number.

```suggestion
                              throw new Exception($"Connected overlay type {Name} has an invalid overlay type name {overlayName}!");
```

2023-11-11 21:12 UTC, Rampastring commented on src/TSMapEditor/Config/ConnectedOverlays.ini
> +; Order: NW, W, SW, N, S, NE, E, SE
Wouldn't it make more sense to follow the order of the `Direction` enum?

That would also allow using `Helpers.VisualDirectionToPoint` in the loop code in `GetOverlayForCell` instead of writing a nested `for` loop.

2023-11-11 21:12 UTC, Rampastring commented on src/TSMapEditor/Mutations/Classes/PlaceConnectedOverlayMutation.cs
> +    /// A mutation that allows placing regular, individual overlay.
Copy/paste mistake in comment

2023-11-11 21:12 UTC, Rampastring commented on src/TSMapEditor/Mutations/Classes/PlaceConnectedOverlayMutation.cs
> +                        });
Won't this potentially add the original overlay info for the same cells multiple times if BrushSize is bigger than 1x1?

As far as I can see, this entire nested `for` loop could be avoided by using `DoForBrushSizeAndSurroundings` and its offset. Possibly with two calls to the function, one for adding the undo data and another for setting the connected overlay.

2023-11-13 18:43 UTC, Rampastring requested changes
Very nice, one nitpick about exception types.

2023-11-13 18:43 UTC, Rampastring commented on src/TSMapEditor/Models/ConnectedOverlayType.cs
> +                    throw new Exception($"Connected overlay type {Name}, frame {i} has an invalid ConnectsTo mask {connectsToString}!");
Throw `INIConfigException` instead of the generic exception type. Applies to all the exceptions thrown here.

2023-11-13 19:04 UTC, ZivDero commented on src/TSMapEditor/Models/ConnectedOverlayType.cs
> +                    throw new Exception($"Connected overlay type {Name}, frame {i} has an invalid ConnectsTo mask {connectsToString}!");
Done

2023-11-13 19:05 UTC, Rampastring approved these changes

2023-11-13 19:06 UTC, merged