Stringtable parsing and StringTableEntry trigger action param
CnCNet/WorldAlteringEditor pull request #96
Opened 2024-01-10 01:12 UTC by MortonPL

* Add `CsfFile` that can read RA2/YR CSF stringtable files,
* Add `[Stringtables]` section to `Config/FileManagerConfig.ini` that specifies which CSF files have to be loaded on startup,
* Add `StringTableParam` trigger action type param type with `SelectStringWindow` GUI.

![image](https://github.com/Rampastring/TSMapEditor/assets/23420063/ea2f4b05-fe06-4da8-b98f-0d6e00b256f9)

2024-01-14 22:42 UTC, Rampastring requested changes

2024-01-14 22:42 UTC, Rampastring commented on src/TSMapEditor/CCEngine/CsfFile.cs
> +            } else
```suggestion
            }
            else
```

2024-01-14 22:42 UTC, Rampastring commented on src/TSMapEditor/Models/Map.cs
> +        public Dictionary<string, CsfString> StringTable { get; private set; } = new();
Since you can't insert new CSF strings into a map and this class is mostly for holding and handling _map_ data, it would make more sense to either move this to Rules or create another class/object for holding the CSF lines.

2024-01-14 22:42 UTC, Rampastring commented on src/TSMapEditor/CCEngine/CCFileManager.cs
> +        }
What is the point of clearing the stringtable list here?

2024-01-18 23:00 UTC, MortonPL commented on src/TSMapEditor/Models/Map.cs
> +        public Dictionary<string, CsfString> StringTable { get; private set; } = new();
Moved to `TSMapEditor.Models.StringTable`, with Map having a public StringTable property.

2024-01-18 23:01 UTC, MortonPL commented on src/TSMapEditor/CCEngine/CCFileManager.cs
> +        }
No point besides moving the ownership from CCFileManager to Map. Removed.

2024-01-20 19:46 UTC, Rampastring approved these changes

2024-01-20 19:47 UTC, merged